 
<form id="form_jobStep1" method="post">
    <h3>Let's start by getting the basics of the job...</h3>

    <div style="min-height: 300px;">
        <fieldset style="float: none; margin: 0 auto; padding: 0; width: 100%;">
            <div class="filter">
                <div style="float: left; width: 48%">
                    <label>Job ID</label> <input type="text" placeholder="Auto Generated by us" readonly="" ng-model="" id="jobID" class="ng-pristine ng-valid">
                </div>
                <div style="float: left; width: 48%">
                    <label style="width: 30%">Internal Job ID<sup>*</sup></label> <input type="text" id="internal_id" name="internal_id" class="ng-pristine ng-valid" required>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="filter">
                <div style="float: left; width: 48%">
                    <label>Specialty<sup>*</sup></label> 
                    <select id="specialty" name="specialty" class="ng-pristine ng-valid parent_speciality" required>
                        <?php 
                        foreach($specialties as $val){ ?>
                            <option value="<?php echo $val['id']; ?>"><?php echo strip_slashes($val['name']); ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div style="float: left; width: 48%">
                    <label style="width: 30%">Sub Specialty<sup>*</sup></label> 
                    <select id="sub_specialty" name="sub_specialty" class="ng-pristine ng-valid sub_speciality" required>
                        <option value=""></option>
                    </select>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="filter">
                <label style="width: 12%">Job Headline<sup>*</sup></label> 
                <input type="text" id="job_headline" name="job_headline" required class="ng-pristine ng-valid" required>
            </div>
            <div class="filter">
                <div style="float: left; width: 48%">
                    <label>Position or Title<sup>*</sup></label> 
                    <input type="text" id="title" name="title" class="ng-pristine ng-valid" required>
                </div>
                <div style="float: left; width: 48%">
                    <label style="width: 30%">Fill By<sup>*</sup></label> 
                    <input type="text" name="fill_by" id="fill_by" class="datepicker" required>
                    
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="filter">
                <div style="float: left; width: 48%">
                    <label>Position Type<sup>*</sup></label> 
                    <select id="position_type" name="position_type" class="ng-pristine ng-valid" onchange="toggleEmploymentLength();" required>
                        <option value="" class="">Select</option>
                        <option value="full_time">Full Time</option>
                        <option value="part_time">Part Time</option>
                        <option value="locum">Locum</option>
                        <option value="temporary">Temporary</option>
                    </select>
                </div>
                <div style="float: left; width: 48%">
                    <div style="display: none;" id="employment_length_div">
                        <label style="width: 30%">Length of Employment<sup>*</sup></label> 
                        <input type="text" id="employment_length" name="employment_length" class="ng-pristine ng-valid" > 
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="filter">
                <label style="width: 12%">Preference on Designation</label> 
                <select style="width: 29%"  id="prefered_designation" name="prefered_designation" class="ng-pristine ng-valid" required>
                    <option value="" class="">Select</option>
                    <option value="D.O">D.O.</option>
                    <option value="M.D">M.D.</option>
                </select>
                
            </div>
        </fieldset>
    </div>
    <div style="text-align: center; margin-top: 20px;">
        <a href="javascript:void(0)" class="btn btn-lg btn-primary post-form-continue-btn" id="continue-step1" data-stepTo="2" data-formValidate="form_jobStep1">Continue</a>
    </div>
</form>
<script>
    function toggleEmploymentLength(){
        var position = $("#position_type").val();
        if(position === "temporary"){
            $("#employment_length_div").show();
            $("#employment_length").attr("required",'true');
        }
        else{
            $("#employment_length_div").hide();
            $("#employment_length").removeAttr("required");
        }
    }
//    $( ".datepicker" ).datepicker();
</script>