<?php //echo load_js("jquery-1.10.2.min.js"); ?>

<?php 
    
    echo load_css('jquery-ui.css','assets/js/jquery_ui/');
    echo load_js("jquery-ui.js","assets/js/jquery_ui/");
            
?>
<form id="form_jobStep1" method="post">
    <h3>Let's start by getting the basics of the job...</h3>

    <div style="min-height: 300px;">
        <fieldset style="float: none; margin: 0 auto; padding: 0; width: 100%;">
            <div class="filter">
                <div style="float: left; width: 48%">
                    <label>Job ID</label> <input type="text" placeholder="Auto Generated by us" readonly="" ng-model="" id="jobID" class="ng-pristine ng-valid">
                </div>
                <div style="float: left; width: 48%">
                    <label style="width: 30%">Internal Job ID<sup>*</sup></label> 
                    <input type="text" id="internal_id" name="internal_id" class="ng-pristine ng-valid" required value="<?php echo (isset($job['internal_id'])) ? $job['internal_id'] : "" ; ?>" >
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="filter">
                <div style="float: left; width: 48%">
                    <label>Specialty<sup>*</sup></label> 
                    <select id="specialty" name="specialty" class="ng-pristine ng-valid parent_speciality" required>
                        <option value="">Select</option>
                        <?php 
                        foreach($specialties as $val){ 
                            $selected = (isset($job['specialty']) && $job['specialty'] == $val['id'] ) ? ' selected="selected" ' : "" ;
                            ?>
                            <option value="<?php echo $val['id']; ?>" <?php echo $selected; ?> ><?php echo strip_slashes($val['name']); ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div style="float: left; width: 48%">
                    <label style="width: 30%">Sub Specialty<sup>*</sup></label> 
                    <select id="sub_specialty" name="sub_specialty" class="ng-pristine ng-valid sub_speciality" required>
                        <?php 
                        if(isset($sub_specialty) && is_array($sub_specialty)){ 
                            foreach($sub_specialty as $sub_spec) { 
                            $selected = (isset($job['sub_specialty']) && $job['sub_specialty'] == $sub_spec['id'] ) ? ' selected="selected" ' : "" ;
                            ?>
                            <option value="<?php echo $sub_spec['id']; ?>" <?php echo $selected; ?> ><?php echo strip_slashes($sub_spec['name']); ?></option>    
                            <?php } 
                        }
                        else{
                        ?>
                        <option value=""></option>
                        <?php } ?>
                    </select>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="filter">
                <label style="width: 12%">Job Headline<sup>*</sup></label> 
                <input type="text" id="job_headline" name="job_headline" required class="ng-pristine ng-valid" required value="<?php echo (isset($job['job_headline'])) ? $job['job_headline'] : "" ; ?>" >
            </div>
            <div class="filter">
                <div style="float: left; width: 48%">
                    <label>Position or Title<sup>*</sup></label> 
                    <input type="text" id="title" name="title" class="ng-pristine ng-valid" required value="<?php echo (isset($job['title'])) ? $job['title'] : "" ; ?>" >
                </div>
                <div style="float: left; width: 48%">
                    <label style="width: 30%">Fill By<sup>*</sup></label> 
                    <input type="text" name="fill_by" id="fill_by" class="datepicker" required value="<?php echo (isset($job['fill_by'])) ? $job['fill_by'] : "" ; ?>" >
                    
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="filter">
                <div style="float: left; width: 48%">
                    <label>Position Type<sup>*</sup></label> 
                    <select id="position_type" name="position_type" class="ng-pristine ng-valid" onchange="toggleEmploymentLength();" required>
                        <option value="" class="">Select</option>
                        <?php
                        $selected = (isset($job['position_type']) && $job['position_type'] == "full_time" ) ? ' selected="selected" ' : "" ;
                        ?>
                        <option value="full_time" <?php echo $selected; ?> >Full Time</option>
                        <?php
                        $selected = (isset($job['position_type']) && $job['position_type'] == "part_time" ) ? ' selected="selected" ' : "" ;
                        ?>
                        <option value="part_time" <?php echo $selected; ?> >Part Time</option>
                        <?php
                        $selected = (isset($job['position_type']) && $job['position_type'] == "locum" ) ? ' selected="selected" ' : "" ;
                        ?>
                        <option value="locum" <?php echo $selected; ?> >Locum</option>
                        <?php
                        $selected = (isset($job['position_type']) && $job['position_type'] == "temporary" ) ? ' selected="selected" ' : "" ;
                        ?>
                        <option value="temporary" <?php echo $selected; ?> >Temporary</option>
                    </select>
                </div>
                <div style="float: left; width: 48%">
                    <?php
                    $style = (isset($job['position_type']) && $job['position_type'] == "temporary" ) ? 'display: block ;' : 'display: none;' ;
                    ?>
                    
                    <div style="<?php echo $style; ?>" id="employment_length_div">
                        <label style="width: 30%">Length of Employment<sup>*</sup></label> 
                        <input type="text" id="employment_length" name="employment_length" class="ng-pristine ng-valid" >
                        
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="filter">
                <label style="width: 12%">Preference on Designation</label> 
                <select style="width: 29%"  id="prefered_designation" name="prefered_designation" class="ng-pristine ng-valid" required>
                    <option value="" class="">Select</option>
                    <?php
                    $selected = (isset($job['prefered_designation']) && $job['prefered_designation'] == "D.O" ) ? ' selected="selected" ' : "" ;
                    ?>
                    <option <?php echo $selected; ?> value="D.O">D.O.</option>
                    <?php
                    $selected = (isset($job['prefered_designation']) && $job['prefered_designation'] == "M.D" ) ? ' selected="selected" ' : "" ;
                    ?>
                    <option <?php echo $selected; ?> value="M.D">M.D.</option>
                </select>
                
            </div>
        </fieldset>
    </div>
    <div style="text-align: center; margin-top: 20px;">
        <a href="javascript:void(0)" class="btn btn-lg btn-primary post-form-continue-btn" id="continue-step1" data-stepTo="2" data-formValidate="form_jobStep1">Continue</a>
    </div>
</form>
<script>
    function toggleEmploymentLength(){
        var position = $("#position_type").val();
        if(position === "temporary"){
            $("#employment_length_div").show();
            $("#employment_length").attr("required",'true');
        }
        else{
            $("#employment_length_div").hide();
            $("#employment_length").removeAttr("required");
        }
    }
    $(".datepicker").datepicker( {"dateFormat":"yy-mm-dd" } );
</script>